version: "3.7"

services:
  backend:
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      - FLASK_ENV=development
      - POSTGRES_URL=postgres
      - POSTGRES_USER=cherelady
      - POSTGRES_PASSWORD=000
      - POSTGRES_DB=new
      - REDIS_URL=redis
    build:
      context: .
      target: backend
    entrypoint:
      - /docker-entrypoint.sh
    ports:
    - 5000:5000
    networks:
      backend:

  postgres:
    restart: always
    image: postgres:13-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=new
      - POSTGRES_USER=cherelady
      - POSTGRES_PASSWORD=000
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      backend:

  redis:
    restart: always
    image: redis:5.0.7
    container_name: redis
    networks:
      backend:

volumes:
  postgres_data:

networks:
  backend: